### ISSUE TITLE
simplify meta introspection

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2922] opened 2021-08-17 02:52 UTC
The various methods on `lake/api.Interface` that scan data structures should be restructured as a query to the same meta-data thereby unify the query model with the lake introspection.

**Comment by philrz** [comment] 2021-08-20 01:29
@mccanne confirmed that this one is a duplicate of #2935, so, closing this one.

**Closed by philrz** 2021-08-20 01:29 UTC
