### ISSUE TITLE
Automated testing of the Zed lake README

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#1179] opened 2020-08-26 15:03 UTC
We have a way to run ( via the `test-heavy` make target) all the zq doc commands in automated testing. 

It would be useful to have a similar facility for the Zed lake README commands to detect breakage with Zed lake changes.

**Comment by philrz** [comment] 2021-04-23 20:45
I just realized we opened a duplicate of this one at #2429 that's written up with more detail. Closing this one as a duplicate.

**Closed by philrz** 2021-04-23 20:45 UTC
