### ISSUE TITLE
Is it possible to reorder fields without providing types?

### ISSUE THREAD

**Issue by zmajeed** [brimdata/zed#4900] opened 2023-11-28 16:31 UTC
This works to reorder fields

```
zq -f table 'order(this, <{avg:int64, min:int64}>)' - <<EOF
{min:7, max:35, avg: 13}
EOF

avg min max
13  7   35
```

But I'd like to reorder fields without needing to know or enter the type for each field - something like this
```
zq -f table 'order(this, {avg, min})' - <<EOF
{min:7, max:35, avg: 13}
EOF

table output encountered non-record value: error({message:"shaper type argument is not a type",on:{avg:13,min:7}})
```

Is reordering only by field names not possible?

I also notice this unexpected output - I expect `avg` to move to first position while all other fields retain their current relative positions
```
zq -f table 'order(this, <{avg:int64}>)' - <<EOF
{min:7, max:35, avg: 13}
EOF

avg max min
13  35  7
```

**Comment by mattnibs** [comment] 2023-11-28 17:30
@zmajeed no this is not currently possible but this is a really good idea / obvious use case for `order`. Will talk with the team about this today.

> I also notice this unexpected output - I expect avg to be move to first position while all other fields retain their current positions

This appears to be a bug.

**Comment by philrz** [comment] 2023-11-28 19:58
@zmajeed: We discussed this one more as a group today. Someone on the team correctly noted that [record expressions](https://zed.brimdata.io/docs/language/expressions#record-expressions) provide an approach for simple reordering without having to specify the fill type. Using your example to specify the order of fields:

```
$ echo '{min:7, max:35, avg: 13}' | zq -f table 'yield {avg,min,max}' -
avg min max
13  7   35
```

Or if you wanted to fill in unspecified fields with those from the original input, you can use the spread operator.

```
$ echo '{min:7, max:35, avg: 13}' | zq -f table 'yield {avg,...this}' -
avg min max
13  7   35
```

FWIW, I just put up a PR #4902 to propose calling this out more explicitly in the docs, since we agree this can be a handy alternative to specifying the full types.

Also, regarding the unexpected order in your last example, on closer review this isn't actually a bug. The [`order` doc](https://zed.brimdata.io/docs/language/functions/order) mentions:

> extra fields in the input are added to the right-hand side, ordered lexicographically

So it's behaving as intended because the string `max` is alphabetically "less than" the string `min`. We actually had to review the docs ourselves to be reminded of this, and after having initially thought it buggy ourselves, we might be open to changing it. Happy to hear if you feel strongly about that.

**Comment by zmajeed** [comment] 2023-11-28 21:00
Thanks - record expressions work - especially with the spread operator! Not sure when I'd need to use `order` then - sorted fieldnames could be useful for diffs or patching - so I wouldn't push to change its behavior

**Comment by philrz** [comment] 2023-11-29 00:34
@zmajeed: Regarding when `order()` might still be handy, it seems the syntax with record expressions can get a little hairy when dealing with nesting. For instance, let's say I start from the [`order` example in the shaping docs](https://zed.brimdata.io/docs/language/shaping#order) and wanted to include a reorder of the inner `port` and `addr` fields as part of doing it via record expression. The best way I could come up with to do this is:

```
$ zq -Z 'yield {kind,client:{port:client.port,addr:client.addr},server:{port:server.port,addr:server.addr},uid}' sample.json
{
    kind: "dns",
    client: {
        port: 41772,
        addr: "10.47.1.100"
    },
    server: {
        port: 53,
        addr: "10.0.0.100"
    },
    uid: "C2zK5f13SbCtKcyiW5"
}
```

By comparison, the way the original example defines the `socket` type one time and references it in the `connection` type is maybe a bit more readable and easier to maintain, though that needs to be weighed against having to specify the types of each individual field, which I recognize is still a pain.

We've had some discussion lately about revisiting some of the shaping functions to make improvements, so we'll keep this use case in mind. Since you seem to be up & running for now though, I'll close this one.

**Closed by philrz** 2023-11-29 00:34 UTC
Labels: community
