### ISSUE TITLE
do proper string escape for zson string/bstring/error etc

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1677] opened 2020-11-22 05:15 UTC
An example of this @philrz bumped into with `zq` commit fc70a73:

```
$ echo '{ref_id:"\x00\x00\x00\x00" (bstring)} (=0)' | zq -Z 'put foo=ref_id:bstring' -
{
    ref_id: "\x00\x00\x00\x00" (bstring),
    foo: "\\x00\\x00\\x00\\x00" (bstring)
} (=0)
```

That is, it was a surprise that casting a type to the same type added another layer of backslash rather than the no-op it was expected it to be. It's kind of a long story, but the tl;dr is that this was encountered while working on shaping. It seems largely cosmetic since both of those print back out the same:

```
$ echo '{ref_id:"\x00\x00\x00\x00" (bstring)} (=0)' | zq -Z 'put foo=ref_id:bstring' - | zq -Z -
{
    ref_id: "\x00\x00\x00\x00" (bstring),
    foo: "\x00\x00\x00\x00" (bstring)
} (=0)
```

However, that seems like it might be wrong, since the ZSON spec says that `\\` would have been interpreted as a genuine backslash character and not the lead-off to a hex escape.

Regarding this example, @mccanne noted:

> The spec is clear on behavior and we just need to bring the code into conformance… [https://github.com/brimsec/zq/blob/master/zng/docs/zson.md#331-string-escape-rules](https://github.com/brimsec/zq/blob/master/zng/docs/zson.md#331-string-escape-rules)

**Comment by philrz** [comment] 2021-04-01 18:53
@mccanne remarked that this is the kind of fix @nwt is really good at. :wink:

**Comment by philrz** [comment] 2021-05-12 20:26
@nwt checked this one out and saw that it's already fixed on `main`. I did a quick binary search and confirmed that this started working as of Zed commit a7522c2, which was associated with #2355 (thanks @mccanne!).

```
$ zq -version
Version: v0.29.0-132-ga7522c26

$ echo '{ref_id:"\x00\x00\x00\x00" (bstring)} (=0)' | zq -Z 'put foo=ref_id:bstring' -
{
    ref_id: "\x00\x00\x00\x00" (bstring),
    foo: "\x00\x00\x00\x00" (bstring)
} (=0)
```

The syntax for casts has since changed, of course, so on the most _current_ Zed such as commit a7522c2, now it looks like:

```
$ zq -version
Version: v0.29.0-132-ga7522c26

$ echo '{ref_id:"\x00\x00\x00\x00" (bstring)} (=0)' | zq -Z 'put foo=bstring(ref_id)' -
{
    ref_id: "\x00\x00\x00\x00" (bstring),
    foo: "\x00\x00\x00\x00" (bstring)
} (=0)
```

Thanks @nwt and @mccanne!

**Closed** 2021-05-29 02:14 UTC
