### ISSUE TITLE
Error parsing union in zed

### ISSUE THREAD

**Issue by mattnibs** [brimdata/zed#4994] opened 2024-01-18 16:41 UTC
```
$ zq -version
Version: v1.12.0-31-g2c0a08de
```

If I create a query with a simple union in it I get a parser error. Observe:

```
$ echo '1' | zq 'yield this + 1((int64,string))' -
zq: error parsing Zed at column 15:
yield this + 1((int64,string))
          === ^ ===
```

**Comment by philrz** [comment] 2024-01-18 19:12
We discussed this one as a team. The problem is not specific to unions, but rather, ZSON type decorators not being accepted in the middle of Zed queries. So for instance this doesn't work either.

```
$ zq -version
Version: v1.12.0-33-g3aab9fd8

$ echo '1' | zq 'yield this + 1(int64)' -
zq: error parsing Zed at column 15:
yield this + 1(int64)
          === ^ ===
```

Instead one would opt for the casting syntax.

```
$ echo '1' | zq 'yield this + int64(1)' -
2
```

Likewise, using the branch from #4995, the casting equivalent of the original repro:

```
$ zq -version
Version: v1.12.0-34-gbd6d1cd5

$ echo '1' | zq 'yield this + <(int64,string)>(1)' -
2
```

Or yet another approach, given that the original was ZSON syntax:

```
$ echo '1' | zq 'yield this + parse_zson("1((int64,string))")' -
2
```

We had a wider discussion about if the parser should be more accepting of ZSON in these contexts, using Node.js's acceptance of JSON values as a point of comparison. We may do more experimenting here.

**Comment by mattnibs** [comment] 2024-01-18 19:13
@philrz I suppose we should close this issue?

**Comment by philrz** [comment] 2024-01-18 19:20
@mattnibs: Yeah. I mostly wanted to capture our discussion in case this comes up again, so assuming you don't see anything grossly inaccurate in that last comment I'll go ahead and close it.

**Closed by philrz** 2024-01-18 19:20 UTC
Labels: bug
