### ISSUE TITLE
Range query not returning anything

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2970] opened 2021-08-27 20:43 UTC
Repro is with Zed commit a2b7592. This is a finding spawned from the verification notes at https://github.com/brimdata/zed/issues/2960#issuecomment-907458624.

```
$ zed -version
Version: v0.29.0-479-ga2b7592f

$ zed lake init
using environment variable ZED_LAKE_ROOT
lake created: /Users/phil/logs

$ zed lake create -p bytes -orderby orig_bytes
pool created: bytes

$ zed lake load -p bytes conn.log.gz
1xKF04dJylry7AoeLro4jieLFBh committed

$ zed lake query -z "from bytes range 20 to 30 | count()"
[no output]

$ echo $?
0
```

However I can see values of the pool key in the specified range, so the lack of output is unexpected.

```
$ zed lake query -z "from bytes | count() by orig_bytes | sort orig_bytes | head 31"
{orig_bytes:0(uint64),count:915494(uint64)}(=0)
{orig_bytes:1,count:171}(0)
{orig_bytes:2,count:2}(0)
{orig_bytes:3,count:200}(0)
{orig_bytes:4,count:101}(0)
{orig_bytes:5,count:8}(0)
{orig_bytes:6,count:235}(0)
{orig_bytes:7,count:26}(0)
{orig_bytes:8,count:48}(0)
{orig_bytes:9,count:87}(0)
{orig_bytes:10,count:12}(0)
{orig_bytes:11,count:96}(0)
{orig_bytes:12,count:82}(0)
{orig_bytes:13,count:3}(0)
{orig_bytes:14,count:28}(0)
{orig_bytes:15,count:23}(0)
{orig_bytes:16,count:45}(0)
{orig_bytes:17,count:15}(0)
{orig_bytes:18,count:69}(0)
{orig_bytes:19,count:64}(0)
{orig_bytes:20,count:34}(0)
{orig_bytes:21,count:22}(0)
{orig_bytes:22,count:48}(0)
{orig_bytes:23,count:36}(0)
{orig_bytes:24,count:253}(0)
{orig_bytes:25,count:248}(0)
{orig_bytes:26,count:26}(0)
{orig_bytes:27,count:1}(0)
{orig_bytes:28,count:14}(0)
{orig_bytes:29,count:11}(0)
{orig_bytes:30,count:9}(0)
```

**Comment by nwt** [comment] 2021-09-30 22:38
This isn't a duplicate of #2965.

It's a mismatch in the treatment of nulls within the comparison functions used during a lake import and that used during a lake read.

During import, `nullsMax` is governed by pool layout order and is `true` for `lake create -orderby orig_bytes` (because the order defaults to ascending).
https://github.com/brimdata/zed/blob/2cf7cff2d861c00370b13bcebe021b54684bd5d5/zbuf/merger.go#L40-L46

During reads, `nullsMax` is always `false`.
https://github.com/brimdata/zed/blob/2cf7cff2d861c00370b13bcebe021b54684bd5d5/expr/extent/span.go#L41-L43

Changing that `false` to `o == order.Asc` causes the Zed query `from bytes range 20 to 30 | count()` to produce the expected result `{count:702(uint64)}`.

**Closed** 2021-10-01 16:56 UTC
Labels: bug

**Comment by philrz** [comment] 2021-10-04 14:54
Verified in Zed commit 14b797c1.

Starting out from Zed commit 2cf7cff that was right before the changes landed from the linked PR, here's the repro steps with current Zed syntax showing the problem was still present.

```
$ zed -version
Version: v0.30.0-59-g2cf7cff2

$ zed lake init
using environment variable ZED_LAKE_ROOT
lake created: /Users/phil/logs

$ zed lake create -orderby orig_bytes bytes
pool created: bytes 1z2vfuR6LUzwaGINrgX09tAkfoX

$ zed lake use -p bytes
Switched to branch "main" on pool "bytes"

$ zed lake load conn.log.gz
1z2vjLyyh1mLdD7naAXzRvPr5Ko committed

$ zed lake query -z "from bytes range 20 to 30 | count()"
[no output]
```

However, if we advance to the next commit 14b797c1 that includes the fixes in the linked PR, now we get the expected count result.

```
$ zed -version
Version: v0.30.0-60-g14b797c1

$ zed lake query -z "from bytes range 20 to 30 | count()"
{count:702(uint64)}
```

Thanks @nwt!
