### ISSUE TITLE
Canonical Zed not showing "put"

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2992] opened 2021-09-01 23:14 UTC
Repro is with Zed commit 59dc184.

The [top-level language README](https://github.com/brimdata/zed/blob/main/docs/language/README.md) describes how the canonical form of:

```
filter match("widget")
| summarize count() by color
| put COLOR := to_upper(color)
```

Can be abbreviated as:

```
widget | count() by color | COLOR := to_upper(color)
```

However, using the tools to try to replicate this, `zc -C` is actually not showing the `put`, though it's including `filter` and `summarize` as the text promises.

```
$ zc -version
Version: v0.29.0-487-g59dc1843

$ zc -C 'widget | count() by color | COLOR := to_upper(color)'
filter match("widget")
| summarize
    count() by color
| COLOR:=to_upper(color)
```

**Comment by mattnibs** [comment] 2021-09-09 21:25
@philrz I did this deliberately in my optional put pr. This is because from the pov of the parser the statement `COLOR:=to_update(color)` is in an ambiguous state: it could be a aggregation or it could be an implied put proc. The semantic pass has the logic to determine this. If you add the `-s` flag you will see what you expect:
```
$ zc -s -C 'COLOR := to_upper(color)`
from (
  (internal reader);
)
| put COLOR:=to_update(color)
```

**Comment by mattnibs** [comment] 2021-09-09 21:32
I'm realizing that the `from` part wouldn't really be desired in this case. As time goes on more of the heavy lifting will shift to the semantic pass. Right this just basically mirrors the shape of the ast.

**Comment by mccanne** [comment] 2021-11-09 02:49
As @mattnibs mentions, this is expected behavior as the put determination is not made until semantic analysis.  So this would give the proper canonical form...
```
zc -s -C widget | count() by color | COLOR := to_upper(color)
from (
  (internal reader);
)
| filter match("widget")
| summarize
    count:=count() by color:=color
| put COLOR:=to_upper(color)
```
while we could force -s if -C is given, that could create different confusion.  We will live as is for now and close this issue.

**Closed by mccanne** 2021-11-09 02:49 UTC
Labels: bug
