### ISSUE TITLE
proc.Catchers in all goroutines

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3387] opened 2021-12-24 19:28 UTC
We need to make sure every goroutine in a flowgraph is protected by a recover() which can be implemented using proc.Catcher.

We should also refactor all the goroutines saw they are all launched and managed in a consistent way to the extent that this is possible.

**Comment by philrz** [comment] 2022-09-12 16:39
Closing as a duplicate of #3382.

**Closed by philrz** 2022-09-12 16:39 UTC
