### ISSUE TITLE
impact of search queries

### ISSUE THREAD

**Issue by badMFboy** [brimdata/zed#4933] opened 2023-12-12 22:09 UTC
Hi all,
Thanks for your useful tool. 
But there is some issue:

Search queries impact each other. I'm trying to send parallel requests to a local lake. As the number of simultaneous queries increases, the search time increases. This is also reproduced when requesting via API.

```
export ZED_LAKE=/mnt/d/TestLake
zed init
zed create  -orderby id,begin_time,end_time test
zed load -use test test_data.zson
```
test_data.zson file with size 1.4G and ~10 millions records like:
{id:0(int32),begin_time:2022-02-24T13:34:23.863019Z,end_time:2026-05-25T13:34:23.863019Z,description:"Description"}(=row)
with random id, begin_time, end_time 

send 1 query:
```
time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()"
9754(uint64)
real    0m0.435s
user    0m1.892s
sys     0m0.081s
```

send 2 same query:
```
time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()" & 
time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()" & wait
[1] 9486
[2] 9487
9754(uint64)

real    0m0.758s
user    0m2.230s
sys     0m0.050s
[1]-  Done                    time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()"
9754(uint64)

real    0m0.766s
user    0m2.153s
sys     0m0.067s
[2]+  Done                    time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()"
```
send 3 same query:
```
time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()" & 
time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()" & time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()" & wait
[1] 9525
[2] 9526
[3] 9528
9754(uint64)

real    0m1.062s
user    0m2.209s
sys     0m0.104s
9754(uint64)

real    0m1.112s
user    0m2.253s
sys     0m0.077s
9754(uint64)

real    0m1.118s
user    0m2.207s
sys     0m0.136s
[1]   Done                    time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()"
[2]-  Done                    time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()"
[3]+  Done                    time zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()"
```

Same request via API and [locust](https://github.com/locustio/locust) performance testing tool:
on locust: set 100 users (100 parallel requests) with spawned rate 1 sec

![total_requests_per_second_1702417094](https://github.com/brimdata/zed/assets/43907043/319609c0-d094-454b-abab-dc8e40e4a7c8)
![response_times_(ms)_1702417094](https://github.com/brimdata/zed/assets/43907043/039788a5-c103-43a0-8541-f8ddccf24a44)
![number_of_users_1702417094](https://github.com/brimdata/zed/assets/43907043/23af92c0-3bd8-4933-aa3b-ccc9ccc86147)

Could you please explain this behaviour.
Thanks in advance

**Comment by philrz** [comment] 2023-12-13 03:56
Hi @badMFboy. Thanks for your interest in Zed!

I'll work on reproducing what you've shown here so we can better explain what's going on. Just to get back to you with one early tip, the way you're creating the pool with multiple keys (e.g., `-orderby id,begin_time,end_time`) is actually unsupported at the moment. You did nothing wrong, as it was a bug on our part that the tools/API were letting that be configured. We've addressed this via #4903 such Zed compiled from tip of `main` would now show:

```
$ zed create  -orderby id,begin_time,end_time test
multiple pool keys not supported
```

...and the same will be true in the next GA release of Zed that will be coming out soon. I'm not sure yet if any of the results you show above would be affected by that, but since I spotted that I figured I'd point it now since when I do my own performance tests I'll be doing it with just a single pool key so our findings are relevant to production configs (I suppose I'll use `id` since you listed it first in your example).

I'll let you know what else we spot after we've finished testing.

**Comment by philrz** [comment] 2023-12-15 03:53
@badMFboy: I've reproduced something similar to the workload you described just to check if I see anything unexpected. What I've found is pretty much a validation of your original statement, which we find unsurprising given the current state of the software:

> As the number of simultaneous queries increases, the search time increases.

I'll illustrate using a simple non-Zed piece of software. To simplify, I'm testing on an AWS `t2.small` instance since it has only a single CPU core. I then wrote a simple Python tool `busyloop.py` that does a finite amount of work (looping `n` times).

```
#!/usr/bin/env python3
import time
import argparse

parser = argparse.ArgumentParser(description='Busy looper')
parser.add_argument('--n', help='How many times to loop', type=int, default=10)
args = parser.parse_args()

print('Busy looping ' + str(args.n) + ' times')

i = 0
while True:
  if i > args.n:
    break
  else:
     i += 1
```

I then wrote a `parallel_busyloop.sh` wrapper script that can invoke it multiple times in parallel and then wait for them all to finish, similar to what you showed.

```
#!/bin/sh
n=0
while [ $n -lt $1 ]; do
  time -p ./busyloop.py --n 20000000 &
  n=$((n + 1))
done
wait
```

If I run it `n` times in parallel, each process takes up about `1/n` of the available CPU and each process takes `n` times longer to finish than when run alone, e.g.:

```
$ ./parallel_busyloop.sh 1
Busy looping 20000000 times
real 2.59
user 2.58
sys 0.00

$ ./parallel_busyloop.sh 2
Busy looping 20000000 times
Busy looping 20000000 times
real 5.18
user 2.57
sys 0.00
real 5.24
user 2.63
sys 0.01

$ ./parallel_busyloop.sh 3
Busy looping 20000000 times
Busy looping 20000000 times
Busy looping 20000000 times
real 7.66
user 2.53
sys 0.01
real 7.74
user 2.57
sys 0.00
real 7.82
user 2.65
sys 0.00
```

And here's a couple back-to-back updates of the per-second CPU usage measured during the run with `3` in parallel showing each Python process getting ~33% of CPU:

```
$ top -b -d 1 | grep python
   1082 ubuntu    20   0   18396  10624   6144 R  33.7   0.5   0:01.21 python3
   1083 ubuntu    20   0   18396  10624   6144 R  32.7   0.5   0:01.21 python3
   1084 ubuntu    20   0   18396  10496   6016 R  32.7   0.5   0:01.21 python3
   1083 ubuntu    20   0   18396  10624   6144 R  34.0   0.5   0:01.55 python3
   1082 ubuntu    20   0   18396  10624   6144 R  33.0   0.5   0:01.54 python3
   1084 ubuntu    20   0   18396  10496   6016 R  33.0   0.5   0:01.54 python3
...
```

What you showed with Zed isn't much different from that. Each of those queries is going to run independently. Since each has an equivalent amount of work to complete, it's going to consume resources proportionately much like we just saw with the generic tool.

Because I wanted to make sure there was nothing odd about your specifics, I created this `zson_gen.py` tool to make data that looks similar to what you showed.

```
#!/usr/bin/env python3

import random
from randomtimestamp import randomtimestamp, random_date, random_time

for i in range(0, 12000000):
  id = int(random.random() * 2147483647)
  begin_time = randomtimestamp(start_year=2021, end_year=2023).isoformat() + 'Z'
  end_time = randomtimestamp(start_year=2021, end_year=2023).isoformat() + 'Z'
  print("{id:" + str(id) + "(int32),begin_time:" + begin_time + ",end_time:" + end_time + ",description:\"Description\"}(=row)")
```

I create the lake/pool and load data from the tool.

```
$ export ZED_LAKE="$(pwd)/test"
$ zed init
$ zed create -orderby id test
$ ./zson_gen.py | zed load -use test -
```

Then I use another wrapper script `parallel.sh` to loop the same Zed query you did.

```
#!/bin/sh
n=0
while [ $n -lt $1 ]; do
  time -p zed query "from test | where begin_time>=cast('2022-12-01',<time>) and begin_time<=cast('2022-12-02',<time>) | count()" &
  n=$((n + 1))
done
wait
```

Since each query is performing a finite amount of work, we see the same effect as before.

```
$ ./parallel.sh 1
10955(uint64)
real 2.45
user 2.38
sys 0.06

$ ./parallel.sh 2
10955(uint64)10955(uint64)
real 5.01
user 2.45
sys 0.05

real 5.01
user 2.44
sys 0.06

$ ./parallel.sh 3
10955(uint64)10955(uint64)10955(uint64)
real 7.42
user 2.41
sys 0.06

real 7.42
user 2.43
sys 0.03

real 7.42
user 2.40
sys 0.07
```

And the per-second `top`:

```
$ top -b -d 1 | grep zed
   1221 ubuntu    20   0 1641712  35072  24320 S  33.3   1.8   0:01.87 zed
   1219 ubuntu    20   0 1641712  33280  23808 S  32.4   1.7   0:01.87 zed
   1220 ubuntu    20   0 1641456  32896  23552 S  32.4   1.6   0:01.87 zed
   1219 ubuntu    20   0 1641712  33792  23808 S  33.0   1.7   0:02.20 zed
   1220 ubuntu    20   0 1641456  33408  23552 S  33.0   1.7   0:02.20 zed
   1221 ubuntu    20   0 1641712  35456  24320 S  33.0   1.8   0:02.20 zed
...
```

There could be more to study/explain depending on if there's changes to the environment, e.g., when there's multiple cores present, and also there may be future Zed enhancements that could come into play here. But I'll start with what's here and ask: Was there something different you expected to see? Is there a particular search system you use that behaves more like what you were expecting to see?

Also, since you seem to be studying performance of the Zed lake, it seems likely you may have a sophisticated use case in mind. We like to understand what people are attempting with the tech to help guide the priorities of our enhancements. If you'd be up to discuss over a Zoom please email support@brimdata.io or ping me `@Phil` on our [community Slack](https://www.brimdata.io/join-slack/). Thanks!

**Comment by philrz** [comment] 2023-12-21 17:16
@badMFboy: I've not heard from you again in the week since my last update, so I'm going to go ahead and close this. Per my last comment, please do reach out if you're up for sharing more detail about what motivated your inquiry. Thanks.

**Closed by philrz** 2023-12-21 17:16 UTC
Labels: community
