### ISSUE TITLE
put needs to handle quiet()

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3370] opened 2021-12-21 21:48 UTC
Unlike group-by and cut, put was written first and doesn't have an easy and adaptive way to modify the output type.  We should refactor and use the type vector stuff.

**Comment by philrz** [comment] 2022-08-29 17:30
I've found this has already been fixed and is a duplicate of #3579. Closing.

**Closed by philrz** 2022-08-29 17:30 UTC
