### ISSUE TITLE
Panic when referencing duplicate field in a record literal

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4440] opened 2023-03-16 17:56 UTC
Repro is with Zed commit d14bc2ce.

```
$ echo "{}" | zq 'yield {x:1,x:2}' -
panic: duplicate field: "x"
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/brimdata/zed/runtime/op.(*Catcher).Pull.func1()
	/Users/phil/work/zed/runtime/op/catcher.go:25 +0x45
panic({0x1cbabe0, 0xc00047eb60})
	/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x213
github.com/brimdata/zed.(*Context).MustLookupTypeRecord(...)
	/Users/phil/work/zed/context.go:154
github.com/brimdata/zed/runtime/expr.(*recordExpr).Eval(0xc0000e3270, {0x3cc3f58, 0xc0006b8300?}, 0xc0000c1b00?)
	/Users/phil/work/zed/runtime/expr/values.go:58 +0x3a5
github.com/brimdata/zed/runtime/op/yield.(*Proc).Pull(0xc000000a50, 0x5?)
	/Users/phil/work/zed/runtime/op/yield/yield.go:31 +0x434
github.com/brimdata/zed/runtime/op.(*Single).Pull(0xc0006b82d0, 0xa0)
	/Users/phil/work/zed/runtime/op/mux.go:134 +0x35
github.com/brimdata/zed/runtime/op.(*Catcher).Pull(0x207bc48?, 0x0?)
	/Users/phil/work/zed/runtime/op/catcher.go:28 +0x6d
github.com/brimdata/zed/runtime.(*Query).Pull(0x3cc2718?, 0x40?)
	/Users/phil/work/zed/runtime/query.go:91 +0x44
github.com/brimdata/zed/zbuf.CopyPuller({0x3cc2718, 0xc0000b9a88}, {0x20703c0, 0xc000000a80})
	/Users/phil/work/zed/zbuf/batch.go:110 +0x53
github.com/brimdata/zed/cli/zq.(*Command).Run(0xc0006e21c0, {0xc0000b0190, 0x2, 0x2})
	/Users/phil/work/zed/cli/zq/command.go:162 +0x78b
github.com/brimdata/zed/pkg/charm.path.run({0xc0006f4018?, 0x1, 0x1}, {0xc0000b0190?, 0x2, 0x0?})
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x8b
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0xc0000061a0?, {0xc0000b0190, 0x2, 0x2})
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x4a
main.main()
	/Users/phil/work/zed/cmd/zq/main.go:11 +0x5d
```

**Comment by nwt** [comment] 2023-08-21 14:13
This is a duplicate of #3365.

**Closed by nwt** 2023-08-21 14:13 UTC
Labels: bug
